version: '3.8'

services:
  frontend:
    image: ghcr.io/mehefujali/unifynt:latest
    container_name: unifynt-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.unifynt.com/api/v1
    networks:
      - unifynt-network

networks:
  unifynt-network:
    external: true
    name: unifynt-network
