export const DEFAULT_SITE_DATA = {
  templateId: "enterprise",
  theme: {
    primary: "#2563EB",
    secondary: "#0F172A",
    background: "#FFFFFF",
    textPrimary: "#0F172A",
  },
  content: {
    header: {
      logoText: "Unifynt Academy",
      logoImage: "",
      navItem1: "Home",
      navItem1Link: "#home",
      navItem2: "About",
      navItem2Link: "#about",
      navItem3: "Programs",
      navItem3Link: "#academics",
      navItem4: "Contact",
      navItem4Link: "#contact",
      extraNavLinks: [],
      ctaText: "Apply Now",
      ctaLink: "/admission",
    },
    hero: {
      layout: "type1",
      badgeText: "Defining the future of education",
      title: "Shape Your",
      subtitle: "Legacy.",
      description: "A premier institution dedicated to academic mastery, character development, and global leadership for the next generation.",
      ctaText: "Enroll Today",
      ctaLink: "#contact",
      secondaryCtaText: "View Curriculum",
      secondaryCtaLink: "#",
      heroImage: "https://images.unsplash.com/photo-1541339907198-e08759df9a13?q=80&w=2070",
      ratingValue: "4.9/5",
      ratingLabel: "Parent Rating",
      ratingAvatars: [
        { url: "https://i.pravatar.cc/150?u=11" },
        { url: "https://i.pravatar.cc/150?u=12" },
        { url: "https://i.pravatar.cc/150?u=13" },
        { url: "https://i.pravatar.cc/150?u=14" },
      ],
      successValue: "100%",
      successLabel: "Success Rate",
      awardText: "National Excellence Award Winner 2025",
      show: true,
    },
    noticeBoard: {
      title: "Institutional Directives",
      show: true,
      items: []
    },
    about: {
      badge: "Our Paradigm",
      titleLine1: "A commitment to",
      titleLine2: "intellectual rigor",
      titleLine3: "and moral clarity.",
      philosophy: "We believe that true education transcends the classroom. It is about fostering a lifelong curiosity and the courage to lead with integrity in an ever-evolving global landscape.",
      aboutImage: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=2070",
      legacyValue: "50+",
      legacyLabel: "Years of Legacy",
      alumniLabel: "Elite Alumni Network",
      councilLabel: "Global Leadership Council",
      show: true,
    },
    stats: {
      items: [
        { label: "Graduation Rate", value: "98%", sub: "Top 1% Nationwide" },
        { label: "Faculty Scholars", value: "120+", sub: "PhD Holders" },
        { label: "Campus Size", value: "15", sub: "Acres of Greenery" },
        { label: "Awards Won", value: "85+", sub: "National Recognition" },
      ],
      show: true,
    },
    features: {
      badge: "Operational Excellence",
      titleLine1: "Why Choose",
      titleLine2: "The Academy.",
      sideImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071",
      rankValue: "#1",
      rankLabel: "QS Ranked School",
      items: [
        { title: "Global Curriculum", desc: "Internationally recognized standards ensuring global competitiveness." },
        { title: "Holistic Growth", desc: "Focus on character, leadership, and emotional intelligence." },
        { title: "Smart Campus", desc: "State-of-the-art technology integrated into every classroom." },
        { title: "Elite Faculty", desc: "Mentorship from world-class educators and industry experts." },
      ],
      show: true,
    },
    academics: {
      badge: "Educational Framework",
      titleLine1: "Academic",
      titleLine2: "Progression.",
      ratingLabel: "Excellence Rating",
      ratingValue: "Tier 1",
      levels: [
        { name: "Primary School", years: "Year 1 - Year 6", desc: "Foundational mastery in core subjects with a focus on cognitive development and creative exploration." },
        { name: "Middle School", years: "Year 7 - Year 9", desc: "Advanced analytical skills and the introduction of specialized fields of study." },
        { name: "High School", years: "Year 10 - Year 12", desc: "Rigorous academic preparation for premier global universities and career paths." },
      ],
      show: true,
    },
    gallery: {
      badge: "Visual Artifacts",
      title: "Campus Environment.",
      description: "Exploring Excellence",
      items: [
        { url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800", colSpan: "col-span-1", rowSpan: "row-span-2" },
        { url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=800", colSpan: "col-span-2", rowSpan: "row-span-1" },
        { url: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=800", colSpan: "col-span-1", rowSpan: "row-span-1" },
        { url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=800", colSpan: "col-span-1", rowSpan: "row-span-1" },
      ],
      show: true,
    },
    testimonials: {
      badge: "Community Voices",
      titleLine1: "Verified",
      titleLine2: "Excellence.",
      items: [
        { name: "Sarah Jenkins", role: "Alumni Parent", quote: "The level of academic rigor and personal attention my son received was transformative." },
        { name: "Dr. Robert Chen", role: "University Professor", quote: "Unifynt graduates enter our university with a maturity and hunger for learning that is rare." },
        { name: "Elena Rodriguez", role: "Head of Student Council", quote: "It's not just a school; it's a community that pushes you to be your best self every day." },
      ],
      show: true,
    },
    contact: {
      title: "Initiate Contact",
      subtitle: "Begin your journey with us today. Our admissions team is ready to guide you.",
      email: "admissions@academy.edu",
      phone: "+1 (555) 000-1234",
      address: "123 Education Lane, Academic City",
      show: true,
    },
    footer: {
      description: "Nurturing intellectual mastery and global leadership for the next generation of pioneers.",
      ctaTitle: "Reach the Summit of Knowledge.",
      show: true,
    },
  },
};
